name: Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          # ref: refs/pull/${{ github.event.number }}/merge

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome
        run: pnpm run check
        id: biome

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "chore: apply formatting"
            git push origin HEAD:${{ github.head_ref }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.LINTER }}
          HUSKY: 0
        # continue-on-error: true

      # - name: Checkout PR branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: refs/pull/${{ github.event.number }}/merge

      # - name: info
      #   run: git diff

      # - name: Commit and Push PR changes
      #   run: |
      #     git config --global user.name 'github-actions[bot]'
      #     git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
      #     git commit -a -m "chore: apply formatting"
      #     git push origin HEAD:refs/pull/${{ github.event.number }}/merge
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
