name: Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Biome
        run: pnpm biome check --error-on-warnings ./src
