name: Publish

on:
  push:
    branches:
      - build

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: check out code
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        id: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN}
          npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}